#pragma once
#include "MarioDefine.h"

#define ID_POSITION_OF_WORLDNUMBER			0
#define ID_POSITION_OF_COIN_1				1
#define ID_POSITION_OF_COIN_2				2
#define ID_POSITION_OF_HEART				3
#define ID_POSITION_OF_POINT_1				4
#define ID_POSITION_OF_POINT_2				5
#define ID_POSITION_OF_POINT_3				6
#define ID_POSITION_OF_POINT_4				7
#define ID_POSITION_OF_POINT_5				8
#define ID_POSITION_OF_POINT_6				9
#define ID_POSITION_OF_POINT_7				10
#define ID_POSITION_OF_TIME_1				11
#define ID_POSITION_OF_TIME_2				12
#define ID_POSITION_OF_TIME_3				13

#define ID_POSITION_OF_SPEED_LEVEL_1		15
#define ID_POSITION_OF_SPEED_LEVEL_2		16
#define ID_POSITION_OF_SPEED_LEVEL_3		17
#define ID_POSITION_OF_SPEED_LEVEL_4		18
#define ID_POSITION_OF_SPEED_LEVEL_5		19
#define ID_POSITION_OF_SPEED_LEVEL_6		20
#define ID_POSITION_OF_SPEED_LEVEL_MAX		21

#define ID_CARD_1_IN_BOARD					22
#define ID_CARD_2_IN_BOARD					23
#define ID_CARD_3_IN_BOARD					24

#define TIME_LIMIT_CHANGE_RENDER_SPEED		150
#define TIME_LIMIT_CHANGE_RENDER_CARD		120

#define ID_FONT_ARROW_WHITE					42
#define ID_FONT_ARROW_BLACK					43
#define ID_FONT_P_TAG_WHITE					44
#define ID_FONT_P_TAG_BLACK					45

#define BOARDGAME_HEIGHT					118

#define DEVIATION_X_WITH_BOARDGAME			20
#define DEVIATION_Y_WITH_BOARDGAME			10

#define	SPEED_LEVEL_1						MARIO_RUNNING_MAX_SPEED*0.4
#define	SPEED_LEVEL_2						MARIO_RUNNING_MAX_SPEED*0.5
#define	SPEED_LEVEL_3						MARIO_RUNNING_MAX_SPEED*0.6
#define	SPEED_LEVEL_4						MARIO_RUNNING_MAX_SPEED*0.7
#define	SPEED_LEVEL_5						MARIO_RUNNING_MAX_SPEED*0.8
#define	SPEED_LEVEL_6						MARIO_RUNNING_MAX_SPEED*0.9
#define	SPEED_LEVEL_MAX						MARIO_RUNNING_MAX_SPEED

//-----------END TILE
#define ENDTITLE_TYPE_FONT					1
#define ENDTITLE_TYPE_CARD					2
