#pragma once

#define FIREBALL_ANI_ROLLING		701

#define FIREBALL_BBOX_WIDTH			18
#define FIREBALL_BBOX_HEIGHT		18
#define FIREBALL_UNTOUCHABLE_TIME	5000

#define FIREBALL_ROLLING_SPEED_X		0.7f
#define FIREBALL_ROLLING_SPEED_Y		0.6f