#pragma once

#define FIREBALL_ANI_ROLLING				701
#define FIREBALL_ANI_DIE_EFFECT				2301

#define FIREBALL_WIDTH						9
#define FIREBALL_HEIGHT						9

#define FIREBALL_BBOX_WIDTH					18
#define FIREBALL_BBOX_HEIGHT				18
#define FIREBALL_UNTOUCHABLE_TIME			5000

#define FIREBALL_ROLLING_SPEED_X			0.7f
#define FIREBALL_ROLLING_SPEED_Y			0.6f

#define FIREBALL_GRAVITY					0.002f

#define FIREBALL_TIME_LIMIT_TO_THROWING		4000
#define FIREBALL_MAX_QUANTITY				2


#define FIREBALL_TYPE_WEAPON				1
#define FIREBALL_TYPE_OF_FLOWER				2

#define MOVING_BRICK_SPEED					0.1f