#pragma once

#define GOOMBA_BBOX_WIDTH	48
#define GOOMBA_BBOX_HEIGHT	48

#define KOOPA_BBOX_WIDTH	48
#define KOOPA_BBOX_HEIGHT	78
#define KOOPA_DIE_BBOX_HEIGHT	48

#define ENEMY_GRAVITY		0.002f

#define GOOMBA_TAN_ANI_WALKING						801
#define GOOMBA_TAN_ANI_DIE							802

#define GOOMBA_RED_ANI_WALKING						803
#define GOOMBA_RED_ANI_DIE							804
#define GOOMBA_RED_ANI_WALKING_WITH_SWINGS			805

#define KOOPA_RED_ANI_WALKING						901
#define KOOPA_RED_ANI_DIE							902
#define KOOPA_RED_ANI_SPIN_DIE_KICK					903
#define KOOPA_RED_ANI_WALKING_WITH_SWINGS			904

#define KOOPA_GREEN_ANI_WALKING						905
#define KOOPA_GREEN_ANI_DIE							906
#define KOOPA_GREEN_ANI_SPIN_DIE_KICK				907
#define KOOPA_GREEN_ANI_WALKING_WITH_SWINGS			908


#define GOOMBA_TAN_STATE_WALKING					81
#define GOOMBA_TAN_STATE_DIE						82

#define GOOMBA_RED_STATE_WALKING					83
#define GOOMBA_RED_STATE_DIE						84
#define GOOMBA_RED_STATE_WALKING_WITH_SWINGS		85

#define KOOPA_RED_STATE_WALKING						91
#define KOOPA_RED_STATE_DIE							92
#define KOOPA_RED_STATE_SPIN_DIE_KICK				93
#define KOOPA_RED_STATE_WALKING_WITH_SWINGS			94

#define KOOPA_GREEN_STATE_WALKING					95
#define KOOPA_GREEN_STATE_DIE						96
#define KOOPA_GREEN_STATE_SPIN_DIE_KICK				97
#define KOOPA_GREEN_STATE_WALKING_WITH_SWINGS		98

#define GOOMBA_WALKING_SPEED			0.08f