#pragma once

#define GOOMBA_BBOX_WIDTH	48
#define GOOMBA_BBOX_HEIGHT	48

#define KOOPA_BBOX_WIDTH	48
#define KOOPA_BBOX_HEIGHT	78
#define KOOPA_DIE_BBOX_HEIGHT	48

#define ENEMY_GRAVITY		0.002f

#define GOOMBA_TAN_ANI_WALKING						801
#define GOOMBA_TAN_ANI_DIE							802

#define GOOMBA_RED_ANI_WALKING						803
#define GOOMBA_RED_ANI_DIE							804
#define GOOMBA_RED_ANI_WALKING_WITH_SWINGS			805

#define KOOPA_RED_ANI_WALKING						901
#define KOOPA_RED_ANI_DIE							902
#define KOOPA_RED_ANI_SPIN_DIE_KICK					903
#define KOOPA_RED_ANI_WALKING_WITH_SWINGS			904

#define KOOPA_GREEN_ANI_WALKING						905
#define KOOPA_GREEN_ANI_DIE							906
#define KOOPA_GREEN_ANI_SPIN_DIE_KICK				907
#define KOOPA_GREEN_ANI_WALKING_WITH_SWINGS			908


#define ENEMY_STATE_WALKING						1
#define ENEMY_STATE_WALKING_WITH_SWINGS			2
#define ENEMY_STATE_DIE							3
#define ENEMY_STATE_SPIN_DIE_KICK				4


#define KOOPA_STATE_TORTOISESHELL				5

#define KOOPA_SPEED_TORTOISESHELL			0.6f

#define GOOMBA_WALKING_SPEED			0.08f

#define KOOPA_HOLDING_DISTANCE_TURN_BACK_X	35
#define KOOPA_HOLDING_DISTANCE_TURN_BACK_Y	-9
#define KOOPA_HOLDING_DISTANCE_TURN_BACK_Y_MARIO_SMALL	10

#define KOOPA_KICKING_AFTER_HOLDING_DISTANCE_X	7
#define KOOPA_KICKING_AFTER_HOLDING_DISTANCE_Y	3

#define ENEMY_DIE_SPEED_X	0.2f;
#define ENEMY_DIE_SPEED_Y	0.5f;

#define KOOPA_WALKING_SPEED_X			0.08f
#define KOOPA_WALKING_WITH_SWINGS_Y		0.7f