#pragma once

#define ITEM_GRAVITY		0.002f

#define COIN_ANI			1001
#define COIN_BBOX_WIDTH		24
#define COIN_BBOX_HEIGHT	42

#define LEAF_ANI			1101
#define LEAF_BBOX_WIDTH		48
#define LEAF_BBOX_HEIGHT	42
#define LEAF_AMPLITUDE		60
#define LEAF_SPEED			0.004f
#define LEAF_SPEED_Y_APPEAR	0.7f

#define MUSHROOM_ANI			1201
#define MUSHROOM_BBOX_WIDTH		47
#define MUSHROOM_BBOX_HEIGHT	48
#define MUSHROOM_SPEED		0.15f
#define MUSHROOM_SPEED_Y_APPEAR	0.05f