#pragma once

#define ITEM_GRAVITY		0.002f

#define COIN_ANI			1001
#define COIN_BBOX_WIDTH		24
#define COIN_BBOX_HEIGHT	42

#define LEAF_ANI			1101
#define LEAF_BBOX_WIDTH		48
#define LEAF_BBOX_HEIGHT	42

#define MUSHROOM_ANI			1201
#define MUSHROOM_BBOX_WIDTH		48
#define MUSHROOM_BBOX_HEIGHT	48