#pragma once

#define ITEM_GRAVITY									0.002f

#define COIN_ANI										1601
#define COIN_BBOX_WIDTH									24
#define COIN_BBOX_HEIGHT								42
#define COIN_SPEED_Y									0.8f

#define STATIC_COIN_ANI									1801
#define COIN_INTO_ESPECIAL_BRICK_ANI					3801
#define LEAF_ANI										1101
#define LEAF_BBOX_WIDTH									48
#define LEAF_BBOX_HEIGHT								42
#define LEAF_AMPLITUDE									60
#define LEAF_SPEED										0.004f
#define LEAF_SPEED_Y_APPEAR								0.88f

#define MUSHROOM_RED_ANI								1201
#define MUSHROOM_GREEN_ANI								4403
#define MUSHROOM_BBOX_WIDTH								47
#define MUSHROOM_BBOX_HEIGHT							48
#define MUSHROOM_SPEED									0.15f
#define MUSHROOM_SPEED_Y_APPEAR							0.05f

#define STATE_ITEM_CURRENT_FIRE_FLOWER					0
#define STATE_ITEM_CURRENT_MUSHROOM						1
#define STATE_ITEM_CURRENT_WHITE_STAR					2
#define STATE_ALREADY_BONUS_GIFT						3

#define ITEM_CURRENT_FIRE_FLOWER_ANI					3201
#define ITEM_CURRENT_MUSHROOM_ANI						3001
#define ITEM_CURRENT_WHITE_STAR_ANI						3101

#define ITEM_CURRENT_FIRE_FLOWER_ANI					3201
#define ITEM_CURRENT_MUSHROOM_ANI						3001
#define ITEM_CURRENT_WHITE_STAR_ANI						3101

#define ITEM_CURRENT_FIRE_FLOWER_ALREADY_BONUS_ANI		3501
#define ITEM_CURRENT_MUSHROOM_ALREADY_BONUS_ANI			3301
#define ITEM_CURRENT_WHITE_STAR_ALREADY_BONUS_ANI		3401


#define TIME_COIN_DIE									7500

#define COIN_TYPE_FROM_QUESTION_BRICK					1
#define COIN_TYPE_STATIC								2
#define COIN_TYPE_FROM_ESPECIAL_BRICK					3

#define MUSHROOM_TYPE_RED								1
#define MUSHROOM_TYPE_GREEN								2

#define LEAF_SPEED_X									0.14f

#define ITEM_FIRE_FLOWER								0
#define ITEM_MUSHROOM									1
#define ITEM_WHITE_STAR									2
#define RANDOM_GIFT_ANI									3601
#define TIME_CHANGE_RANDOM_GIFT							100
#define RANDOM_GIFT_SPEED_Y								0.2f

#define ID_CARD_FIRE_FLOWER								3
#define ID_CARD_MUSHROOM								2
#define ID_CARD_WHITE_STAR								4