#pragma once

#define QUESTION_BRICK_ANI						501
#define QUESTION_BRICK_DIE_ANI					502

#define QUESTION_BRICK_BBOX_WIDTH				48
#define QUESTION_BRICK_BBOX_HEIGHT				48

#define QUESTION_BRICK_TYPE_HAS_COIN			1
#define QUESTION_BRICK_TYPE_HAS_ESPECIAL_ITEM	2