#pragma once

#define QUESTION_BRICK_ANI						501
#define QUESTION_BRICK_DIE_ANI					502
#define ESPECIAL_BRICK_ANI						2701
#define FRAGMENT_ESPECIAL_BRICK_ANI				2801

#define BUTTON_P_ANI							2901
#define BUTTON_P_PRESSED_ANI					2902

#define QUESTION_BRICK_BBOX_WIDTH				48
#define QUESTION_BRICK_BBOX_HEIGHT				48

#define QUESTION_BRICK_TYPE_HAS_COIN			1
#define QUESTION_BRICK_TYPE_HAS_ESPECIAL_ITEM	2


#define POINT_TYPE_100							100
#define POINT_TYPE_1000							1000
#define POINT_TYPE_1UP							1

#define POINT_100_ANI							2501
#define POINT_1000_ANI							4401
#define POINT_1UP_ANI							4402

#define WIDTH_POINT								39
#define HEIGHT_POINT							30

#define TIME_LIMIT_FRAGMENT_DISAPEAR			5000

#define ESPECIAL_BRICK_TYPE_HAS_EMPTY			1
#define ESPECIAL_BRICK_TYPE_HAS_BUTTON_P		2
#define ESPECIAL_BRICK_TYPE_HAS_1UP				3