#pragma once

#define QUESTION_BRICK_ANI						501
#define QUESTION_BRICK_DIE_ANI					502
#define ESPECIAL_BRICK_ANI						2701
#define FRAGMENT_ESPECIAL_BRICK_ANI				2801

#define BUTTON_P_ANI							2901
#define BUTTON_P_PRESSED_ANI					2902

#define QUESTION_BRICK_BBOX_WIDTH				48
#define QUESTION_BRICK_BBOX_HEIGHT				48

#define QUESTION_BRICK_TYPE_HAS_COIN			1
#define QUESTION_BRICK_TYPE_HAS_ESPECIAL_ITEM	2